# Generated by Django 2.1.7 on 2019-05-21 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('farmer_land_village_id', models.CharField(max_length=100)),
                ('ssp', models.CharField(max_length=15)),
                ('land_village', models.CharField(max_length=15)),
                ('applied', models.CharField(max_length=15)),
                ('mcp', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'app_treatment',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=20)),
                ('sec_code', models.CharField(max_length=20)),
                ('sec_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'division',
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csi_code', models.CharField(max_length=20)),
                ('sysno', models.CharField(max_length=100)),
                ('csi_name', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=15)),
                ('ryot_photo', models.CharField(max_length=15)),
                ('rno', models.CharField(max_length=15)),
                ('village_id', models.CharField(max_length=15)),
                ('litrary_status', models.CharField(max_length=15)),
                ('person_id', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'farmer',
            },
        ),
        migrations.CreateModel(
            name='LandVillage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_village_code', models.CharField(max_length=20)),
                ('village_id', models.CharField(max_length=20)),
                ('distance', models.CharField(max_length=20)),
                ('west', models.CharField(max_length=20)),
                ('south', models.CharField(max_length=20)),
                ('land_village', models.CharField(max_length=20)),
                ('plot_no', models.CharField(max_length=20)),
                ('east', models.CharField(max_length=20)),
                ('north', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'landvillage',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=100)),
                ('division_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='piatrika_form.Division')),
            ],
            options={
                'db_table': 'village',
            },
        ),
    ]
