# Generated by Django 2.1.7 on 2019-05-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piatrika_form', '0002_auto_20190522_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='village_code',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farmer',
            name='csi_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='ryot_photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
