# Generated by Django 2.1.7 on 2019-05-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piatrika_form', '0003_auto_20190522_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='litrary_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='person_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='rno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='sysno',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='village_id',
            field=models.CharField(max_length=20),
        ),
    ]
