# Generated by Django 2.1.7 on 2019-05-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piatrika_form', '0004_auto_20190522_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtreatment',
            name='applied',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationtreatment',
            name='farmer_land_village_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationtreatment',
            name='land_village',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationtreatment',
            name='mcp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='applicationtreatment',
            name='ssp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='ryot_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
