# Generated by Django 2.2.1 on 2019-05-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piatrika_form', '0005_auto_20190522_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(default='', max_length=70)),
                ('bank_code', models.CharField(default='', max_length=70)),
                ('branch_address', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(default='', max_length=70)),
                ('crop_scientific_name', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'crop',
            },
        ),
        migrations.CreateModel(
            name='FarmerBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(default='', max_length=70)),
                ('farmer_id', models.CharField(default='', max_length=70)),
                ('bank_id', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'farmer_bank',
            },
        ),
        migrations.CreateModel(
            name='FarmerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_to_csi', models.CharField(default='', max_length=70)),
                ('person_id', models.CharField(default='', max_length=70)),
                ('relationship_type', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'farmer_relation',
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.CharField(default='', max_length=70)),
                ('season_farmer_id', models.CharField(default='', max_length=70)),
                ('season_land_village_id', models.CharField(default='', max_length=70)),
                ('person_id', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'guarantor',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sb_acno', models.CharField(default='', max_length=70)),
                ('ledger_no', models.CharField(default='', max_length=70)),
                ('folio_no', models.CharField(default='', max_length=70)),
                ('farmer_id', models.CharField(default='', max_length=70)),
                ('loan_no', models.CharField(default='', max_length=70)),
                ('loan_ac_ledger_no', models.CharField(default='', max_length=70)),
                ('loan_ac_folio_no', models.CharField(default='', max_length=70)),
                ('payment_mode', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'loan',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=70)),
                ('last_name', models.CharField(default='', max_length=70)),
                ('middle_name', models.CharField(default='', max_length=70)),
                ('city', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=70)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(default='', max_length=70)),
                ('number', models.CharField(default='', max_length=70)),
                ('person_id', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'phone',
            },
        ),
        migrations.CreateModel(
            name='PlotVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(default='', max_length=70)),
                ('advice_given', models.CharField(default='', max_length=70)),
                ('identification', models.CharField(default='', max_length=70)),
                ('time_stamp', models.DateField(blank=True, null=True)),
                ('season_id', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'plot_visit',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_start', models.DateField(blank=True, null=True)),
                ('extent', models.CharField(default='', max_length=70)),
                ('expected_harvesting', models.CharField(default='', max_length=70)),
                ('expected_planting', models.CharField(default='', max_length=70)),
                ('farmers_id', models.CharField(default='', max_length=70)),
                ('land_village_id', models.CharField(default='', max_length=70)),
                ('current_variety', models.CharField(default='', max_length=70)),
                ('previous_variety', models.CharField(default='', max_length=70)),
                ('plant_type', models.CharField(default='', max_length=70)),
                ('total_acres', models.CharField(default='', max_length=70)),
                ('measurement_acres', models.CharField(default='', max_length=70)),
                ('estimated_yield', models.CharField(default='', max_length=70)),
                ('offer_no', models.CharField(default='', max_length=70)),
                ('offer_date', models.CharField(default='', max_length=70)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('agreement_acre', models.CharField(default='', max_length=70)),
                ('agreement_tonne', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'season',
            },
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(default='', max_length=70)),
                ('crop_id', models.CharField(default='', max_length=70)),
                ('variety_scientific_name', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'variety',
            },
        ),
    ]
