# Generated by Django 2.2.1 on 2019-05-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piatrika_form', '0006_bank_crop_farmerbank_farmerrelation_guarantor_loan_person_phone_plotvisit_season_variety'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varietee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variety', models.CharField(default='', max_length=70)),
                ('crop_id', models.CharField(default='', max_length=70)),
                ('variety_scientific_name', models.CharField(default='', max_length=70)),
            ],
            options={
                'db_table': 'varietees',
            },
        ),
        migrations.RenameModel(
            old_name='Division',
            new_name='DivisionModel',
        ),
        migrations.DeleteModel(
            name='Variety',
        ),
        migrations.AlterModelTable(
            name='applicationtreatment',
            table='applicationtreatments',
        ),
        migrations.AlterModelTable(
            name='bank',
            table='banks',
        ),
        migrations.AlterModelTable(
            name='crop',
            table='crops',
        ),
        migrations.AlterModelTable(
            name='divisionmodel',
            table='divisionmodels',
        ),
        migrations.AlterModelTable(
            name='farmer',
            table='farmers',
        ),
        migrations.AlterModelTable(
            name='farmerbank',
            table='farmerbanks',
        ),
        migrations.AlterModelTable(
            name='farmerrelation',
            table='farmerrelations',
        ),
        migrations.AlterModelTable(
            name='guarantor',
            table='guarantors',
        ),
        migrations.AlterModelTable(
            name='landvillage',
            table='landvillages',
        ),
        migrations.AlterModelTable(
            name='loan',
            table='loans',
        ),
        migrations.AlterModelTable(
            name='person',
            table='persons',
        ),
        migrations.AlterModelTable(
            name='phone',
            table='phones',
        ),
        migrations.AlterModelTable(
            name='plotvisit',
            table='plotvisits',
        ),
        migrations.AlterModelTable(
            name='season',
            table='seasons',
        ),
        migrations.AlterModelTable(
            name='village',
            table='villages',
        ),
    ]
