# Generated by Django 2.2.1 on 2019-05-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piatrika_form', '0007_auto_20190525_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divisionmodel',
            old_name='sec_code',
            new_name='section_code',
        ),
        migrations.RenameField(
            model_name='divisionmodel',
            old_name='sec_name',
            new_name='section_name',
        ),
        migrations.RenameField(
            model_name='farmerbank',
            old_name='farmer_id',
            new_name='Farmers_id',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='farmer_id',
            new_name='Farmers_id',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='farmers_id',
            new_name='Farmers_id',
        ),
        migrations.AddField(
            model_name='applicationtreatment',
            name='application_treatment',
            field=models.CharField(default='apt1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='LatLng',
            field=models.CharField(default='latlng1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='latitude',
            field=models.CharField(default='lat1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmer',
            name='longitude',
            field=models.CharField(default='lng1', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationtreatment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationtreatment',
            name='farmer_land_village_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='farmerrelation',
            name='person_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=70, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='agreement_acre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='agreement_tonne',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='expected_harvesting',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='expected_planting',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='land_village_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='offer_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
