# Generated by Django 2.2 on 2019-05-27 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piatrika_form', '0009_auto_20190526_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationtreatment',
            name='land_village',
        ),
        migrations.AlterField(
            model_name='applicationtreatment',
            name='farmer_land_village_id',
            field=models.CharField(max_length=20),
        ),
    ]
